services:
  certbot:
    image: certbot/certbot
    container_name: certbotcontainer
    environment:
      - CERTBOT_DOMAIN=${CERTBOT_DOMAIN}
    volumes:
      - ./ssl:/etc/letsencrypt
      - ./static:/usr/share/nginx/html/
    command: certonly --webroot --webroot-path=/usr/share/nginx/html -d ${CERTBOT_DOMAIN} --agree-tos --email mohd.ahsasn@thewitslab.com --no-eff-email --keep-until-expiring --force-renewal --keep
    depends_on:
      - nginx-certbot


  nginx-certbot:
    image: nginx:alpine
    container_name: nginx-certbot
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./static:/usr/share/nginx/html/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf



